# Generated by Django 4.1 on 2022-09-02 01:46

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_appuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category_one",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("image", models.ImageField(upload_to=store.models.category_image)),
            ],
        ),
    ]
