# Generated by Django 4.1 on 2022-09-02 04:00

from django.db import migrations, models
import django.utils.timezone
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_category_one"),
    ]

    operations = [
        migrations.DeleteModel(name="Category_one",),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to=store.models.category_image
            ),
            preserve_default=False,
        ),
    ]
