# Generated by Django 4.1 on 2022-09-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_animal_category_discription_subcategory_size"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="discription",),
        migrations.RemoveField(model_name="category", name="image",),
        migrations.AddField(
            model_name="product",
            name="author",
            field=models.CharField(default="admin", max_length=255),
        ),
    ]
