# Generated by Django 4.1 on 2022-09-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_remove_category_discription_remove_category_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
